name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: deku
          authToken: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: "Run nix flake check"
        run: nix flake check
      - name: "Build deku via flakes"
        run: nix build .#deku
